name: Test

on: [ push, pull_request ]

jobs:
  busted:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Busted
        uses: lunarmodules/busted@v2
